#!/usr/bin/env python3
"""
Combined No Spread bot. Generated by OddsManager.
Buys No at median bid-ask pricing, split from max_combined. Only include
checked stakes. Uses median of each market's No bid-ask; averages across
stakes. Offers at target prices summing to max_combined.
Run from project root: python combined_no_Event.py
"""
import json
import os
import sys

_here = os.path.dirname(os.path.abspath(__file__))
_root = _here
while _root and not os.path.isdir(os.path.join(_root, "market_making")):
    _parent = os.path.dirname(_root)
    if _parent == _root:
        break
    _root = _parent
if not _root:
    _root = os.path.dirname(_here)
if _root not in sys.path:
    sys.path.insert(0, _root)
os.chdir(_root)

from market_making.combined_no_bot import run

CONFIG_JSON = r'''{"event_ticker":"KXTX33D-26","env":"prod","check_interval_sec":30,"max_combined":99,"shares":5,"tickers":["KXTX33D-26-JJOH","KXTX33D-26-CALL"],"alert_webhook_url":null,"always_post_first":true}'''

if __name__ == "__main__":
    config = json.loads(CONFIG_JSON)
    run(config)
