#!/usr/bin/env python3
"""
Kalshi per-stake market maker. Generated by OddsManager.
Run from project root: python mm_Event_26.py
Or save as market_making/config.json and run: python -m market_making.bot
"""
import json
import os
import sys

_here = os.path.dirname(os.path.abspath(__file__))
_root = _here
while _root and not os.path.isdir(os.path.join(_root, "market_making")):
    _parent = os.path.dirname(_root)
    if _parent == _root:
        break
    _root = _parent
if not _root:
    _root = os.path.dirname(_here)
if _root not in sys.path:
    sys.path.insert(0, _root)
os.chdir(_root)

from market_making.bot import run

CONFIG_JSON = r'''{"event_ticker":"KXTXSENDPRIMARYMOV-26MAR03","env":"prod","check_interval_sec":30,"alert_webhook_url":null,"stakes":[{"ticker":"KXTXSENDPRIMARYMOV-26MAR03-JTAL-P59","title":"Will the margin of victory for James Talarico in the first round of the 2026 Texas Senate Democratic primary be between 18% and 100%?","shares":1000,"side":"no","yes_price":null,"no_price":90,"pct_reload":75,"repost_base":"market_best_offer","cents_off":1,"max_shares":2400}]}'''

if __name__ == "__main__":
    config = json.loads(CONFIG_JSON)
    run(config)
